[versions]
activity = "1.11.0"
activityCompose = "1.11.0"
activityKtx = "1.11.0"
agp = "8.11.2"
androidCoreKtx = "1.17.0"
androidLifecycleRuntimeKtx = "2.9.4"
appcompat = "1.7.1"
bouncycastle = "1.79"
compose = "1.7.6"
composeBom = "2025.09.00"
compose-material3 = "1.3.1"
composePayButton = "1.1.0"
coilCompose = "3.3.0"
coilNetworkOkhttp = "3.3.0"
coilTest = "3.3.0"
datastorePreferences = "1.1.7"
dokka = "2.0.0"
espressoCore = "3.5.0"
firebaseBom = "34.4.0"
google-services-plugin = "4.4.4"
io-mockk = "1.14.6"
jetbrains-kotlinx-test = "1.10.2"
junitJupiter = "5.13.4"
jreleaser-plugin = "1.15.0"
junitVersion = "1.3.0"
kotlin = "2.2.20"
kotlinxCoroutinesPlayServices = "1.10.2"
kotlinSerialization = "2.2.20"
kotlinxSerializationJson = "1.9.0"
playServicesWallet = "19.4.0"
slf4jApi = "2.0.17"
sonarqube-plugin = "6.3.1.5724"
uiTooling = "1.9.1"
uiTestJunit4Android = "1.9.3"
runtime = "1.0.0-alpha06"
junitKtx = "1.3.0"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidCoreKtx" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidLifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidLifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidLifecycleRuntimeKtx" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
bouncycastle-bcprov = { module = "org.bouncycastle:bcprov-jdk15to18", version.ref = "bouncycastle" }
compose-pay-button = { module = "com.google.pay.button:compose-pay-button", version.ref = "composePayButton" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
io-mockk = { group = "io.mockk", name = "mockk", version.ref = "io-mockk" }
io-mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "io-mockk" }
io-mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "io-mockk" }
jetbrains-kotlinx-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "jetbrains-kotlinx-test" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
play-services-wallet = { module = "com.google.android.gms:play-services-wallet", version.ref = "playServicesWallet" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
androidx-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "uiTestJunit4Android" }
androidx-runtime = { group = "androidx.xr.runtime", name = "runtime", version.ref = "runtime" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
io-coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
io-coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
io-coil-test = { module = "io.coil-kt.coil3:coil-test", version.ref = "coilTest" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services-plugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "kotlin-parcelize" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube-plugin" }

